resources:
  repositories:
    - repository: VulnerableCode
      type: git
      name: JavaVulnerableCode
      ref: master

steps:
- checkout: VulnerableCode
- task: YashhJaggi.cxsast.cx-scan-task.Application security testing@2022
  displayName: 'Application security testing'
  inputs:
    projectName: 'Sprint 11'
    syncMode: true
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 9.3SAST
    fullTeamName: /CxServer
    projectcustomfields: 'Key1:Value100'
    customfields: 'Key1:Value10'
    comment: 'Generating YAML File'
    generatePDFReport: true