resources:
  repositories:
    - repository: VulnerableCode
      type: git
      name: JavaVulnerableCode
      ref: master

stages:
- stage: Deploy
  pool: 
    name: Default
  jobs:
  - job: Job
    steps:
    - checkout: VulnerableCode    
    - task: YashhJaggi.cxsast.cx-scan-task.Application security testing@2022
      displayName: 'Application security testing'
      inputs:
        projectName: 'Sprint 11'
        enableProxy: false
        enableSastScan: true
        CheckmarxService: '9.4SAST'
        fullTeamName: '/CxServer'
        incScan: false
        projectcustomfields: 'Key1:Value100'
        customfields: 'Key1:Value10'
        comment: 'Generating YAML File'
        generatePDFReport: true
        enableDependencyScan: false
